/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;
import javax.servlet.ServletOutputStream;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author Junior
 */
public class Laporan extends javax.swing.JFrame {
    Connection koneksi;    
    
    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laporan1 = new tampilan.Laporan();
        btnBarang = new javax.swing.JButton();
        btnSup = new javax.swing.JButton();
        btnKon = new javax.swing.JButton();
        btnKar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnPembelian = new javax.swing.JButton();
        btnPenjualan = new javax.swing.JButton();
        btnDPembelian = new javax.swing.JButton();
        btnDPenjualan = new javax.swing.JButton();
        datePembelian = new com.toedter.calendar.JDateChooser();
        datePenjualan = new com.toedter.calendar.JDateChooser();
        btnSPenjualan = new javax.swing.JButton();
        btnSPembelian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBarang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Barang.png"))); // NOI18N
        btnBarang.setText("Laporan Barang");
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnSup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Supplier.png"))); // NOI18N
        btnSup.setText("Laporan Supplier");
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        btnKon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Konsumen.png"))); // NOI18N
        btnKon.setText("Laporan Konsumen");
        btnKon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonActionPerformed(evt);
            }
        });

        btnKar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnKar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Karyawan.png"))); // NOI18N
        btnKar.setText("Laporan Karyawan");
        btnKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Laporan Toko Buku Junior");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Klik Menu Sesuai Pilihan Anda");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/iLaporan.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Menu.png"))); // NOI18N
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPembelian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/uBeli.png"))); // NOI18N
        btnPembelian.setText("Laporan Pembelian");
        btnPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembelianActionPerformed(evt);
            }
        });

        btnPenjualan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Umum.png"))); // NOI18N
        btnPenjualan.setText("Laporan Penjualan");
        btnPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenjualanActionPerformed(evt);
            }
        });

        btnDPembelian.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Beli.png"))); // NOI18N
        btnDPembelian.setText("Detail Pembelian");
        btnDPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPembelianActionPerformed(evt);
            }
        });

        btnDPenjualan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Detail.png"))); // NOI18N
        btnDPenjualan.setText("Detail Penjualan");
        btnDPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDPenjualanActionPerformed(evt);
            }
        });

        btnSPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Cari.png"))); // NOI18N
        btnSPenjualan.setText("Cari");
        btnSPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPenjualanActionPerformed(evt);
            }
        });

        btnSPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tampilan/Cari.png"))); // NOI18N
        btnSPembelian.setText("Cari");
        btnSPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPembelianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporan1Layout = new javax.swing.GroupLayout(laporan1);
        laporan1.setLayout(laporan1Layout);
        laporan1Layout.setHorizontalGroup(
            laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporan1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createSequentialGroup()
                        .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(laporan1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnKon, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(laporan1Layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(btnKar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(laporan1Layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createSequentialGroup()
                        .addComponent(datePembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(btnDPembelian, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createSequentialGroup()
                        .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPenjualan, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSPenjualan, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDPenjualan))
                            .addComponent(datePenjualan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(laporan1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btnPembelian))
                            .addGroup(laporan1Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(btnSPembelian)))))
                .addGap(76, 76, 76))
        );
        laporan1Layout.setVerticalGroup(
            laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createSequentialGroup()
                .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporan1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporan1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createSequentialGroup()
                        .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datePenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSPenjualan)
                            .addComponent(btnSPembelian))
                        .addGap(30, 30, 30)
                        .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPenjualan)
                            .addComponent(btnPembelian))
                        .addGap(28, 28, 28)
                        .addGroup(laporan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDPenjualan)
                            .addComponent(btnDPembelian))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporan1Layout.createSequentialGroup()
                        .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnKon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonActionPerformed
        // TODO add your handling code here:
        //koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\konsumen.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi);
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnKonActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\barang.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi);
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\supplier.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi);
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSupActionPerformed

    private void btnKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKarActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\karyawan.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi);
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnKarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenjualanActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\penjualan.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi);
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnPenjualanActionPerformed

    private void btnDPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPenjualanActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\dePenjualan.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi);
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnDPenjualanActionPerformed

    private void btnPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembelianActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\pembelian.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi);
            JasperViewer.viewReport(jp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnPembelianActionPerformed

    private void btnDPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDPembelianActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\dPembelian.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi);
            JasperViewer.viewReport(jp);
        } catch (SQLException | JRException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnDPembelianActionPerformed

    private void btnSPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPenjualanActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\jual.jrxml";

            HashMap param = new HashMap ();           
            
            java.util.Date tanggal = new java.util.Date(datePenjualan.getDate().getTime());
            
            param.put ("Tanggal", tanggal);

            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, koneksi);
            JasperViewer.viewReport(jp);
        } catch (SQLException | JRException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSPenjualanActionPerformed

    private void btnSPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPembelianActionPerformed
        // TODO add your handling code here:
        try {
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/bo","root","");
            String report = "C:\\Users\\Junior\\Documents\\NetBeansProjects\\JavaApplication6\\src\\laporan\\beli.jrxml";

            HashMap param = new HashMap ();

            java.util.Date tanggal = new java.util.Date(datePembelian.getDate().getTime());
            
            param.put ("Tanggal", tanggal);

            JasperReport jr = JasperCompileManager.compileReport(report);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, koneksi);
            JasperViewer.viewReport(jp);
        } catch (SQLException | JRException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnSPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Laporan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnDPembelian;
    private javax.swing.JButton btnDPenjualan;
    private javax.swing.JButton btnKar;
    private javax.swing.JButton btnKon;
    private javax.swing.JButton btnPembelian;
    private javax.swing.JButton btnPenjualan;
    private javax.swing.JButton btnSPembelian;
    private javax.swing.JButton btnSPenjualan;
    private javax.swing.JButton btnSup;
    private com.toedter.calendar.JDateChooser datePembelian;
    private com.toedter.calendar.JDateChooser datePenjualan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private tampilan.Laporan laporan1;
    // End of variables declaration//GEN-END:variables
}
